const exercises = [
{t:'Pozdrav bez parametara',d:'Početni',c:'() => vrednost',p:'Napravi arrow funkciju `pozdrav` koja nema parametre i vraća string `Zdravo!`.',s:'const pozdrav = () => {\n  // tvoj kod\n}',h:'Kada nema parametara koristi prazne zagrade: `() => ...`.',a:'const pozdrav = () => "Zdravo!";',n:'pozdrav',x:[["await fn()",'Zdravo!']]},
{t:'Kvadrat broja',d:'Početni',c:'Jedan parametar',p:'Napravi `kvadrat(n)` koja vraća kvadrat broja.',s:'const kvadrat = n => {\n  // tvoj kod\n}',h:'Kvadrat je `n * n`.',a:'const kvadrat = n => n * n;',n:'kvadrat',x:[["await fn(4)",16],["await fn(-3)",9]]},
{t:'Sabiranje',d:'Početni',c:'Više parametara',p:'Napravi `saberi(a, b)` koja vraća zbir dva broja.',s:'const saberi = (a, b) => {\n  // tvoj kod\n}',h:'Kod više parametara koristi `(a, b)`.',a:'const saberi = (a, b) => a + b;',n:'saberi',x:[["await fn(2,3)",5],["await fn(-5,2)",-3]]},
{t:'Da li je broj pozitivan?',d:'Početni',c:'Boolean rezultat',p:'Napravi `jePozitivan(n)` koja vraća true samo ako je broj veći od 0.',s:'const jePozitivan = n => {\n  // tvoj kod\n}',h:'Poređenje `n > 0` već vraća true ili false.',a:'const jePozitivan = n => n > 0;',n:'jePozitivan',x:[["await fn(5)",true],["await fn(0)",false]]},
{t:'Puno ime',d:'Početni',c:'Template literal',p:'Napravi `punoIme(ime, prezime)` koja vraća tekst `Ime Prezime`.',s:'const punoIme = (ime, prezime) => {\n  // tvoj kod\n}',h:'Probaj `${ime} ${prezime}`.',a:'const punoIme = (ime, prezime) => `${ime} ${prezime}`;',n:'punoIme',x:[["await fn('Igor','Gasi')",'Igor Gasi']]},
{t:'Paran broj',d:'Početni',c:'Operator %',p:'Napravi `jeParan(n)` koja vraća true za parne brojeve.',s:'const jeParan = n => {\n  // tvoj kod\n}',h:'Paran broj ima ostatak 0 pri deljenju sa 2.',a:'const jeParan = n => n % 2 === 0;',n:'jeParan',x:[["await fn(8)",true],["await fn(7)",false]]},
{t:'Veći od dva broja',d:'Početni',c:'Ternary operator',p:'Napravi `veci(a, b)` koja vraća veći od dva broja.',s:'const veci = (a, b) => {\n  // tvoj kod\n}',h:'`uslov ? akoDa : akoNe`.',a:'const veci = (a, b) => a > b ? a : b;',n:'veci',x:[["await fn(9,4)",9],["await fn(3,8)",8]]},
{t:'Podrazumevani parametar',d:'Početni',c:'Default parametar',p:'Napravi `pozdravi(ime = "goste")` koja vraća `Zdravo, <ime>!`.',s:'const pozdravi = (ime = "goste") => {\n  // tvoj kod\n}',h:'Default vrednost je već u parametru.',a:'const pozdravi = (ime = "goste") => `Zdravo, ${ime}!`;',n:'pozdravi',x:[["await fn()",'Zdravo, goste!'],["await fn('Igor')",'Zdravo, Igor!']]},
{t:'Objekat iz parametara',d:'Lako',c:'Implicitni return objekta',p:'Napravi `napraviKorisnika(ime, godine)` koja vraća objekat `{ ime, godine }`.',s:'const napraviKorisnika = (ime, godine) => {\n  // tvoj kod\n}',h:'Za implicitno vraćanje objekta koristi `({ ... })`.',a:'const napraviKorisnika = (ime, godine) => ({ ime, godine });',n:'napraviKorisnika',x:[["JSON.stringify(await fn('Igor',30))",'{"ime":"Igor","godine":30}']]},
{t:'Celsius u Fahrenheit',d:'Lako',c:'Matematički izraz',p:'Napravi `uFahrenheit(c)` po formuli `c * 9/5 + 32`.',s:'const uFahrenheit = c => {\n  // tvoj kod\n}',h:'Primeni formulu direktno.',a:'const uFahrenheit = c => c * 9 / 5 + 32;',n:'uFahrenheit',x:[["await fn(0)",32],["await fn(100)",212]]},
{t:'Poslednji element niza',d:'Lako',c:'Indeksiranje niza',p:'Napravi `poslednji(niz)` koja vraća poslednji element niza.',s:'const poslednji = niz => {\n  // tvoj kod\n}',h:'Poslednji indeks je `niz.length - 1`.',a:'const poslednji = niz => niz[niz.length - 1];',n:'poslednji',x:[["await fn([1,2,3])",3]]},
{t:'Punoletstvo',d:'Lako',c:'Ternary ili if',p:'Napravi `status(godine)` koja vraća `punoletan` za 18 ili više, inače `maloletan`.',s:'const status = godine => {\n  // tvoj kod\n}',h:'Možeš koristiti ternary operator.',a:'const status = godine => godine >= 18 ? "punoletan" : "maloletan";',n:'status',x:[["await fn(18)",'punoletan'],["await fn(12)",'maloletan']]},
{t:'Bezbedno korisničko ime',d:'Lako',c:'Optional chaining i ??',p:'Napravi `korisnickoIme(user)` koja vraća username, a ako ga nema vraća `Nepoznat`.',s:'const korisnickoIme = user => {\n  // tvoj kod\n}',h:'Probaj `user?.username ?? "Nepoznat"`.',a:'const korisnickoIme = user => user?.username ?? "Nepoznat";',n:'korisnickoIme',x:[["await fn({username:'igor'})",'igor'],["await fn(null)",'Nepoznat']]},
{t:'Dupliraj svaki broj',d:'Srednje',c:'Array.map + arrow callback',p:'Napravi `dupliraj(niz)` koja vraća novi niz gde je svaki broj pomnožen sa 2.',s:'const dupliraj = niz => {\n  // koristi map\n}',h:'`niz.map(x => ...)`.',a:'const dupliraj = niz => niz.map(x => x * 2);',n:'dupliraj',x:[["JSON.stringify(await fn([1,2,3]))",'[2,4,6]']]},
{t:'Filtriraj pozitivne',d:'Srednje',c:'Array.filter + arrow callback',p:'Napravi `pozitivni(niz)` koja vraća samo brojeve veće od 0.',s:'const pozitivni = niz => {\n  // koristi filter\n}',h:'Filter zadržava element kada callback vrati true.',a:'const pozitivni = niz => niz.filter(x => x > 0);',n:'pozitivni',x:[["JSON.stringify(await fn([-2,0,3,5]))",'[3,5]']]},
{t:'Suma niza',d:'Srednje',c:'Array.reduce + arrow callback',p:'Napravi `suma(niz)` koja sabira sve brojeve.',s:'const suma = niz => {\n  // koristi reduce\n}',h:'`reduce((acc, x) => acc + x, 0)`.',a:'const suma = niz => niz.reduce((acc, x) => acc + x, 0);',n:'suma',x:[["await fn([1,2,3,4])",10],["await fn([])",0]]},
{t:'Imena korisnika',d:'Srednje',c:'map nad objektima',p:'Napravi `imena(users)` koja iz niza objekata vraća niz njihovih username vrednosti.',s:'const imena = users => {\n  // tvoj kod\n}',h:'Mapiraj `user => user.username`.',a:'const imena = users => users.map(user => user.username);',n:'imena',x:[["JSON.stringify(await fn([{username:'a'},{username:'b'}]))",'["a","b"]']]},
{t:'Aktivni korisnici',d:'Srednje',c:'filter nad objektima',p:'Napravi `aktivni(users)` koja vraća samo korisnike gde je `active === true`.',s:'const aktivni = users => {\n  // tvoj kod\n}',h:'U filter callback-u proveri `user.active`.',a:'const aktivni = users => users.filter(user => user.active === true);',n:'aktivni',x:[["JSON.stringify(await fn([{id:1,active:true},{id:2,active:false}]))",'[{"id":1,"active":true}]']]},
{t:'Pronađi korisnika po ID-u',d:'Srednje',c:'Array.find',p:'Napravi `pronadji(users, id)` koja vraća korisnika čiji je id jednak prosleđenom ID-u.',s:'const pronadji = (users, id) => {\n  // koristi find\n}',h:'Find vraća prvi element koji prođe uslov.',a:'const pronadji = (users, id) => users.find(user => user.id === id);',n:'pronadji',x:[["JSON.stringify(await fn([{id:1},{id:2}],2))",'{"id":2}']]},
{t:'Da li su svi punoletni?',d:'Srednje',c:'Array.every',p:'Napravi `sviPunoletni(users)` koja vraća true samo ako svi imaju najmanje 18 godina.',s:'const sviPunoletni = users => {\n  // koristi every\n}',h:'Every proverava svaki element.',a:'const sviPunoletni = users => users.every(user => user.godine >= 18);',n:'sviPunoletni',x:[["await fn([{godine:20},{godine:30}])",true],["await fn([{godine:20},{godine:16}])",false]]},
{t:'Da li postoji admin?',d:'Srednje',c:'Array.some',p:'Napravi `imaAdmina(users)` koja vraća true ako bar jedan korisnik ima role `admin`.',s:'const imaAdmina = users => {\n  // koristi some\n}',h:'Some vraća true ako makar jedan element prođe.',a:'const imaAdmina = users => users.some(user => user.role === "admin");',n:'imaAdmina',x:[["await fn([{role:'user'},{role:'admin'}])",true]]},
{t:'Destructuring parametra',d:'Srednje',c:'Destructuring objekta',p:'Napravi `opis({name, age})` koja vraća string `name ima age godina`.',s:'const opis = ({ name, age }) => {\n  // tvoj kod\n}',h:'Vrednosti su već izvučene iz objekta kroz parametar.',a:'const opis = ({ name, age }) => `${name} ima ${age} godina`;',n:'opis',x:[["await fn({name:'Igor',age:30})",'Igor ima 30 godina']]},
{t:'Rest parametri',d:'Srednje',c:'...rest',p:'Napravi `saberiSve(...brojevi)` koja sabira proizvoljan broj argumenata.',s:'const saberiSve = (...brojevi) => {\n  // tvoj kod\n}',h:'`brojevi` je niz.',a:'const saberiSve = (...brojevi) => brojevi.reduce((a,b) => a+b, 0);',n:'saberiSve',x:[["await fn(1,2,3,4)",10],["await fn()",0]]},
{t:'Funkcija vraća funkciju',d:'Napredno',c:'Higher-order funkcija',p:'Napravi `pomnoziSa(faktor)` koja vraća novu arrow funkciju koja množi broj sa tim faktorom.',s:'const pomnoziSa = faktor => {\n  // vrati funkciju\n}',h:'Možeš napisati `faktor => broj => ...`.',a:'const pomnoziSa = faktor => broj => broj * faktor;',n:'pomnoziSa',x:[["await fn(3)(4)",12]]},
{t:'Callback kao argument',d:'Napredno',c:'Funkcija kao vrednost',p:'Napravi `primeni(vrednost, callback)` koja vraća `callback(vrednost)`.',s:'const primeni = (vrednost, callback) => {\n  // tvoj kod\n}',h:'Callback je samo funkcija koju možeš pozvati.',a:'const primeni = (vrednost, callback) => callback(vrednost);',n:'primeni',x:[["await fn(5, x => x*2)",10]]},
{t:'Sortiranje po godinama',d:'Napredno',c:'sort callback',p:'Napravi `sortirajPoGodinama(users)` koja vraća novi niz sortiran rastuće po age, bez menjanja originala.',s:'const sortirajPoGodinama = users => {\n  // tvoj kod\n}',h:'Kopiraj niz sa `[...users]`, pa koristi sort.',a:'const sortirajPoGodinama = users => [...users].sort((a,b) => a.age - b.age);',n:'sortirajPoGodinama',x:[["JSON.stringify(await fn([{age:30},{age:20},{age:25}]))",'[{"age":20},{"age":25},{"age":30}]']]},
{t:'Lanac filter + map',d:'Napredno',c:'Kombinovanje array metoda',p:'Napravi `kvadratiParnih(niz)` koja zadrži samo parne brojeve, pa ih kvadrira.',s:'const kvadratiParnih = niz => {\n  // filter pa map\n}',h:'Lančano koristi `.filter(...).map(...)`.',a:'const kvadratiParnih = niz => niz.filter(n => n % 2 === 0).map(n => n*n);',n:'kvadratiParnih',x:[["JSON.stringify(await fn([1,2,3,4]))",'[4,16]']]},
{t:'Grupisanje po stanju',d:'Napredno',c:'reduce nad objektom',p:'Napravi `grupisiPoState(servisi)` koja vraća objekat sa brojem servisa po `state`.',s:'const grupisiPoState = servisi => {\n  // koristi reduce\n}',h:'U reduce-u povećavaj `acc[item.state]`.',a:'const grupisiPoState = servisi => servisi.reduce((acc,item) => { acc[item.state]=(acc[item.state]||0)+1; return acc; }, {});',n:'grupisiPoState',x:[["JSON.stringify(await fn([{state:'new'},{state:'done'},{state:'new'}]))",'{"new":2,"done":1}']]},
{t:'Arrow HTTP handler',d:'Napredno',c:'Arrow funkcija kao handler',p:'Napravi `napraviHandler(poruka)` koja vraća `(req, res) => res.json({ message: poruka })`.',s:'const napraviHandler = poruka => {\n  // vrati (req, res) => ...\n}',h:'Funkcija treba da vrati drugu arrow funkciju.',a:'const napraviHandler = poruka => (req, res) => res.json({ message: poruka });',n:'napraviHandler',x:[["(()=>{let out;const res={json:x=>out=x};fn('Zdravo')({},res);return JSON.stringify(out)})()",'{"message":"Zdravo"}']]},
{t:'Handler sa req.params',d:'Napredno',c:'req i res',p:'Napravi `handler(req, res)` koji iz `req.params.id` uzima ID i šalje `{ id: Number(id) }` kroz `res.json`.',s:'const handler = (req, res) => {\n  // tvoj kod\n}',h:'`req.params.id` je najčešće string.',a:'const handler = (req, res) => res.json({ id: Number(req.params.id) });',n:'handler',x:[["(()=>{let out;const res={json:x=>out=x};fn({params:{id:'17'}},res);return JSON.stringify(out)})()",'{"id":17}']]},
{t:'Handler sa query parametrom',d:'Napredno',c:'req.query',p:'Napravi `searchHandler(req, res)` koji šalje `{ q: req.query.q ?? "" }`.',s:'const searchHandler = (req, res) => {\n  // tvoj kod\n}',h:'Koristi nullish operator `??`.',a:'const searchHandler = (req, res) => res.json({ q: req.query.q ?? "" });',n:'searchHandler',x:[["(()=>{let out;const res={json:x=>out=x};fn({query:{q:'telefon'}},res);return JSON.stringify(out)})()",'{"q":"telefon"}']]},
{t:'Async arrow funkcija',d:'Napredno',c:'async/await',p:'Napravi `duploAsync(n)` kao async arrow funkciju koja vraća n * 2.',s:'const duploAsync = async n => {\n  // tvoj kod\n}',h:'Async funkcija automatski vraća Promise.',a:'const duploAsync = async n => n * 2;',n:'duploAsync',x:[["await fn(6)",12]]},
{t:'Await callback',d:'Napredno',c:'await unutar arrow funkcije',p:'Napravi `ucitaj(loader)` koja čeka `loader()` i vraća njegov rezultat.',s:'const ucitaj = async loader => {\n  // tvoj kod\n}',h:'Za vežbu je dovoljno `return await loader()`.',a:'const ucitaj = async loader => await loader();',n:'ucitaj',x:[["await fn(async()=>\"podaci\")",'podaci']]},
{t:'Async transformacija',d:'Napredno',c:'Promise.all + map',p:'Napravi `obradi(niz, callback)` koja čeka async callback za svaki element i vraća novi niz.',s:'const obradi = async (niz, callback) => {\n  // Promise.all + map\n}',h:'`Promise.all(niz.map(x => callback(x)))`.',a:'const obradi = async (niz, callback) => Promise.all(niz.map(x => callback(x)));',n:'obradi',x:[["JSON.stringify(await fn([1,2,3], async x => x*3))",'[3,6,9]']]},
{t:'Factory za filter',d:'Napredno',c:'Closure',p:'Napravi `veceOd(min)` koja vraća funkciju pogodnu za `filter`.',s:'const veceOd = min => {\n  // vrati callback\n}',h:'Vrati `vrednost => vrednost > min`.',a:'const veceOd = min => vrednost => vrednost > min;',n:'veceOd',x:[["JSON.stringify([1,5,10].filter(fn(4)))",'[5,10]']]},
{t:'Kompozicija funkcija',d:'Teško',c:'Higher-order kompozicija',p:'Napravi `compose(f, g)` koja vraća funkciju `x => f(g(x))`.',s:'const compose = (f, g) => {\n  // tvoj kod\n}',h:'Prvo se poziva g(x), pa f nad rezultatom.',a:'const compose = (f, g) => x => f(g(x));',n:'compose',x:[["await fn(x=>x+1,x=>x*2)(5)",11]]},
{t:'Curry sabiranje',d:'Teško',c:'Currying',p:'Napravi `curryAdd(a)` koja vraća funkciju za b, pa funkciju za c, i vraća a+b+c.',s:'const curryAdd = a => {\n  // vrati b => c => ...\n}',h:'Može stati u jednu liniju: `a => b => c => ...`.',a:'const curryAdd = a => b => c => a + b + c;',n:'curryAdd',x:[["await fn(1)(2)(3)",6]]},
{t:'Express-like route factory',d:'Teško',c:'Factory koja vraća req/res handler',p:'Napravi `route(serviceFn)` koja vraća async `(req, res)` handler i šalje `await serviceFn()` kroz `res.json`.',s:'const route = serviceFn => {\n  // vrati async handler\n}',h:'Vrati `async (req,res) => res.json(await serviceFn())`.',a:'const route = serviceFn => async (req, res) => res.json(await serviceFn());',n:'route',x:[["await (async()=>{let out;const res={json:x=>out=x};await fn(async()=>({ok:true}))({},res);return JSON.stringify(out)})()",'{"ok":true}']]},
{t:'Safe wrapper za async funkciju',d:'Teško',c:'Arrow funkcija + try/catch + higher-order',p:'Napravi `safe(fnToRun)` koja vraća async funkciju. Ona treba da vrati rezultat `fnToRun()`, a ako dođe do greške da vrati string `GRESKA`.',s:'const safe = fnToRun => {\n  // vrati async funkciju\n}',h:'Vrati `async () => { try { ... } catch(e) { ... } }`.',a:'const safe = fnToRun => async () => { try { return await fnToRun(); } catch (e) { return "GRESKA"; } };',n:'safe',x:[["await fn(async()=>42)()",42],["await fn(async()=>{throw new Error('x')})()",'GRESKA']]},
{t:'Route sa req.params ID-em',d:'Teško',c:'Express stil + closure + async',p:'Napravi `routeById(serviceFn)` koja vraća async `(req,res)` handler. Handler treba da uzme `Number(req.params.id)`, prosledi ga u `serviceFn(id)` i rezultat pošalje kroz `res.json`.',s:'const routeById = serviceFn => {\n  // vrati async (req, res) => ...\n}',h:'U handleru prvo napravi broj iz `req.params.id`, zatim `await serviceFn(id)`.',a:'const routeById = serviceFn => async (req, res) => res.json(await serviceFn(Number(req.params.id)));',n:'routeById',x:[["await (async()=>{let out;const res={json:x=>out=x};await fn(async id=>({id}))({params:{id:'9'}},res);return JSON.stringify(out)})()",'{"id":9}']]}
];

const state={current:Number(localStorage.getItem('arrowCurrent')||0),solved:JSON.parse(localStorage.getItem('arrowSolved')||'[]')};
const $=id=>document.getElementById(id);
const el={list:$('list'),num:$('num'),difficulty:$('difficulty'),title:$('title'),desc:$('desc'),concept:$('concept'),editor:$('editor'),feedback:$('feedback'),hintBox:$('hintBox'),hintText:$('hintText'),solutionBox:$('solutionBox'),solutionCode:$('solutionCode'),progressText:$('progressText'),bar:$('bar'),levelText:$('levelText'),prev:$('prev'),next:$('next'),check:$('check'),hint:$('hint'),solution:$('solution'),resetBtn:$('resetBtn')};
const key=i=>`arrowAnswer_${i}`;
function save(){localStorage.setItem('arrowCurrent',String(state.current));localStorage.setItem('arrowSolved',JSON.stringify(state.solved))}
function saveAnswer(){localStorage.setItem(key(state.current),el.editor.value)}
function renderList(){el.list.innerHTML='';exercises.forEach((x,i)=>{const b=document.createElement('button');b.className='task'+(i===state.current?' active':'')+(state.solved.includes(i)?' solved':'');b.innerHTML=`<span class="task-num">${i+1}</span><span class="task-title">${x.t}</span><span class="tick">${state.solved.includes(i)?'✓':''}</span>`;b.onclick=()=>{saveAnswer();state.current=i;save();render()};el.list.appendChild(b)})}
function renderExercise(){const x=exercises[state.current];el.num.textContent=`Zadatak ${state.current+1} / ${exercises.length}`;el.difficulty.textContent=x.d;el.title.textContent=x.t;el.desc.textContent=x.p;el.concept.textContent=x.c;el.editor.value=localStorage.getItem(key(state.current))??x.s;el.hintText.textContent=x.h;el.solutionCode.textContent=x.a;el.feedback.className='box hidden';el.hintBox.classList.add('hidden');el.solutionBox.classList.add('hidden');el.prev.disabled=state.current===0;el.next.disabled=state.current===exercises.length-1}
function renderProgress(){el.progressText.textContent=`${state.solved.length} / ${exercises.length} rešeno`;el.bar.style.width=`${state.solved.length/exercises.length*100}%`;const n=state.current+1;el.levelText.textContent=`Nivo ${n>32?5:n>24?4:n>16?3:n>8?2:1}`}
function render(){renderList();renderExercise();renderProgress()}
function compile(code,target){return new Function(`"use strict";${code};if(typeof ${target}==='undefined')throw new Error("Nije pronađena funkcija '${target}'. Proveri naziv.");return ${target};`)()}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
async function test(){saveAnswer();const x=exercises[state.current];let fn;try{fn=compile(el.editor.value,x.n)}catch(e){show(false,`Greška u kodu: ${esc(e.message)}`);return}const out=[];for(let i=0;i<x.x.length;i++){const [expr,expected]=x.x[i];try{const run=new Function('fn',`return (async()=>(${expr}))()`);const actual=await run(fn);out.push({ok:Object.is(actual,expected),actual,expected,n:i+1})}catch(e){out.push({ok:false,actual:'Greška: '+e.message,expected,n:i+1})}}const ok=out.every(r=>r.ok);show(ok,`${ok?'Odlično — svi testovi su prošli.':'Neki testovi nisu prošli.'}<ul class="tests">${out.map(r=>`<li class="${r.ok?'pass':'fail'}">Test ${r.n}: ${r.ok?'PROŠAO':`NIJE PROŠAO — dobijeno <code>${esc(r.actual)}</code>, očekivano <code>${esc(r.expected)}</code>`}</li>`).join('')}</ul>`);if(ok&&!state.solved.includes(state.current)){state.solved.push(state.current);state.solved.sort((a,b)=>a-b);save();renderList();renderProgress()}}
function show(ok,html){el.feedback.className='box '+(ok?'success':'error');el.feedback.innerHTML=html}
el.editor.oninput=saveAnswer;
el.prev.onclick=()=>{if(state.current>0){saveAnswer();state.current--;save();render()}};
el.next.onclick=()=>{if(state.current<exercises.length-1){saveAnswer();state.current++;save();render()}};
el.check.onclick=test;
el.hint.onclick=()=>el.hintBox.classList.toggle('hidden');
el.solution.onclick=()=>el.solutionBox.classList.toggle('hidden');
el.resetBtn.onclick=()=>{if(confirm('Obrisati sav napredak i sačuvana rešenja?')){localStorage.removeItem('arrowCurrent');localStorage.removeItem('arrowSolved');for(let i=0;i<exercises.length;i++)localStorage.removeItem(key(i));state.current=0;state.solved=[];render()}};
render();
